base_url = "https://jamie.sh"

build_search_index = true
generate_feed = true
compile_sass = true
minify_html = true
taxonomies = [
    { name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = false
favicon = "/icon/favicon.png"
theme = "auto"

menu = [
    { name = "posts", url = "/", weight = 1 },
    { name = "about", url = "/about", weight = 2 },
]

custom_css = []

[extra.analytics]
enabled = false
